name: tracing
channels:
    - defaults
dependencies:
    - numpy
    - networkx
    - matplotlib
    - pandas
    - pytest
    - scipy
    - seaborn
    - requests
    - pip
    - jupyter
    - jupyterlab
    - tqdm
    - pip:
          - EoN
          - ortools
